# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1532, 902)
        MainWindow.setMinimumSize(QtCore.QSize(1532, 902))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./src/ICON/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(26, 25, 57);\n"
"          color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_fcous_img = QtWidgets.QLabel(self.centralwidget)
        self.label_fcous_img.setMinimumSize(QtCore.QSize(480, 480))
        self.label_fcous_img.setMaximumSize(QtCore.QSize(480, 480))
        self.label_fcous_img.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 3px solid rgb(63, 65, 68);\n"
"\n"
"")
        self.label_fcous_img.setText("")
        self.label_fcous_img.setObjectName("label_fcous_img")
        self.verticalLayout.addWidget(self.label_fcous_img)
        self.label_slide = QtWidgets.QLabel(self.centralwidget)
        self.label_slide.setMinimumSize(QtCore.QSize(480, 160))
        self.label_slide.setMaximumSize(QtCore.QSize(480, 160))
        self.label_slide.setStyleSheet("    QLabel {\n"
"        background-image: url(\'./src/480.png\'); \n"
"        background-repeat: no-repeat;\n"
"        background-position: center;\n"
"    }\n"
"")
        self.label_slide.setText("")
        self.label_slide.setObjectName("label_slide")
        self.verticalLayout.addWidget(self.label_slide)
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setMinimumSize(QtCore.QSize(480, 0))
        self.textEdit_log.setMaximumSize(QtCore.QSize(480, 16777215))
        self.textEdit_log.setStyleSheet("background-color: black; border: 3px solid rgb(63, 65, 68);\n"
"")
        self.textEdit_log.setObjectName("textEdit_log")
        self.verticalLayout.addWidget(self.textEdit_log)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_slide = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_slide.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_slide.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_slide.setStyleSheet("background-color: black; border: 3px solid rgb(63, 65, 68);\n"
"")
        self.lineEdit_slide.setObjectName("lineEdit_slide")
        self.verticalLayout_2.addWidget(self.lineEdit_slide)
        self.textEdit_infor_only = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_infor_only.setMinimumSize(QtCore.QSize(0, 170))
        self.textEdit_infor_only.setMaximumSize(QtCore.QSize(16777215, 170))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_infor_only.setFont(font)
        self.textEdit_infor_only.setStyleSheet("background-color: black; border: 3px solid rgb(63, 65, 68);\n"
"")
        self.textEdit_infor_only.setObjectName("textEdit_infor_only")
        self.verticalLayout_2.addWidget(self.textEdit_infor_only)
        self.label_camera = QtWidgets.QLabel(self.centralwidget)
        self.label_camera.setMinimumSize(QtCore.QSize(640, 640))
        self.label_camera.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 3px solid rgb(63, 65, 68);\n"
"\n"
"")
        self.label_camera.setText("")
        self.label_camera.setObjectName("label_camera")
        self.verticalLayout_2.addWidget(self.label_camera)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setMinimumSize(QtCore.QSize(350, 20))
        self.label_16.setMaximumSize(QtCore.QSize(350, 20))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_20.addWidget(self.label_16)
        self.comboBox_multiple = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_multiple.setMinimumSize(QtCore.QSize(113, 40))
        self.comboBox_multiple.setMaximumSize(QtCore.QSize(350, 40))
        self.comboBox_multiple.setStyleSheet("    QComboBox {\n"
"        background-color: rgb(135, 206, 250);;  /* 设置背景颜色 */\n"
"        border: 1px solid gray;  /* 设置边框样式 */\n"
"        color: black;  /* 设置文本颜色 */\n"
"        padding: 1px 18px 1px 3px;\n"
"        min-width: 6em;\n"
"        border-radius: 10px;  /* 设置圆角半径 */\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: top right;\n"
"        width: 20px;\n"
"        border-left-width: 1px;\n"
"        border-left-color: darkgray;\n"
"        border-left-style: solid;\n"
"        border-top-right-radius: 3px;\n"
"        border-bottom-right-radius: 3px;\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #F6F7FA, stop:1 #DCDEE4);\n"
"    }")
        self.comboBox_multiple.setObjectName("comboBox_multiple")
        self.comboBox_multiple.addItem("")
        self.verticalLayout_20.addWidget(self.comboBox_multiple)
        self.verticalLayout_5.addLayout(self.verticalLayout_20)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setMinimumSize(QtCore.QSize(350, 20))
        self.label_10.setMaximumSize(QtCore.QSize(350, 20))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_18.addWidget(self.label_10)
        self.comboBox_mode = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_mode.setMinimumSize(QtCore.QSize(113, 40))
        self.comboBox_mode.setMaximumSize(QtCore.QSize(350, 40))
        self.comboBox_mode.setStyleSheet("    QComboBox {\n"
"        background-color: rgb(135, 206, 250);;  /* 设置背景颜色 */\n"
"        border: 1px solid gray;  /* 设置边框样式 */\n"
"        color: black;  /* 设置文本颜色 */\n"
"        padding: 1px 18px 1px 3px;\n"
"        min-width: 6em;\n"
"        border-radius: 10px;  /* 设置圆角半径 */\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: top right;\n"
"        width: 20px;\n"
"        border-left-width: 1px;\n"
"        border-left-color: darkgray;\n"
"        border-left-style: solid;\n"
"        border-top-right-radius: 3px;\n"
"        border-bottom-right-radius: 3px;\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #F6F7FA, stop:1 #DCDEE4);\n"
"    }")
        self.comboBox_mode.setObjectName("comboBox_mode")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.verticalLayout_18.addWidget(self.comboBox_mode)
        self.verticalLayout_5.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setMinimumSize(QtCore.QSize(350, 20))
        self.label_11.setMaximumSize(QtCore.QSize(350, 20))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_19.addWidget(self.label_11)
        self.comboBox_region = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_region.setMinimumSize(QtCore.QSize(113, 40))
        self.comboBox_region.setMaximumSize(QtCore.QSize(350, 40))
        self.comboBox_region.setStyleSheet("    QComboBox {\n"
"        background-color: rgb(135, 206, 250);;  /* 设置背景颜色 */\n"
"        border: 1px solid gray;  /* 设置边框样式 */\n"
"        color: black;  /* 设置文本颜色 */\n"
"        padding: 1px 18px 1px 3px;\n"
"        min-width: 6em;\n"
"        border-radius: 10px;  /* 设置圆角半径 */\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: top right;\n"
"        width: 20px;\n"
"        border-left-width: 1px;\n"
"        border-left-color: darkgray;\n"
"        border-left-style: solid;\n"
"        border-top-right-radius: 3px;\n"
"        border-bottom-right-radius: 3px;\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #F6F7FA, stop:1 #DCDEE4);\n"
"    }")
        self.comboBox_region.setObjectName("comboBox_region")
        self.comboBox_region.addItem("")
        self.comboBox_region.addItem("")
        self.comboBox_region.addItem("")
        self.verticalLayout_19.addWidget(self.comboBox_region)
        self.verticalLayout_5.addLayout(self.verticalLayout_19)
        self.pushButton_save_setup = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_setup.setMinimumSize(QtCore.QSize(120, 40))
        self.pushButton_save_setup.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_save_setup.setStyleSheet("QPushButton {\n"
"        background-color: rgb(135, 206, 250);\n"
"        color: white;\n"
"        border-radius: 20px;\n"
"        padding: 10px;\n"
"        font-size: 16px;\n"
"        border: none;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(70, 130, 180);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(30, 144, 255);\n"
"    }\n"
"    QPushButton:disabled {\n"
"        background-color: rgb(192, 192, 192);\n"
"    }")
        self.pushButton_save_setup.setObjectName("pushButton_save_setup")
        self.verticalLayout_5.addWidget(self.pushButton_save_setup)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setMinimumSize(QtCore.QSize(350, 20))
        self.label_12.setMaximumSize(QtCore.QSize(350, 20))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_initialize = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_initialize.setMinimumSize(QtCore.QSize(120, 40))
        self.pushButton_initialize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_initialize.setStyleSheet("QPushButton {\n"
"        background-color: rgb(135, 206, 250);\n"
"        color: white;\n"
"        border-radius: 20px;\n"
"        padding: 10px;\n"
"        font-size: 16px;\n"
"        border: none;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(70, 130, 180);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(30, 144, 255);\n"
"    }\n"
"    QPushButton:disabled {\n"
"        background-color: rgb(192, 192, 192);\n"
"    }")
        self.pushButton_initialize.setObjectName("pushButton_initialize")
        self.horizontalLayout.addWidget(self.pushButton_initialize)
        self.pushButton_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run.setMinimumSize(QtCore.QSize(120, 40))
        self.pushButton_run.setMaximumSize(QtCore.QSize(120, 40))
        self.pushButton_run.setStyleSheet("QPushButton {\n"
"        background-color: rgb(135, 206, 250);\n"
"        color: white;\n"
"        border-radius: 20px;\n"
"        padding: 10px;\n"
"        font-size: 16px;\n"
"        border: none;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(70, 130, 180);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(30, 144, 255);\n"
"    }\n"
"    QPushButton:disabled {\n"
"        background-color: rgb(192, 192, 192);\n"
"    }")
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout.addWidget(self.pushButton_run)
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setMinimumSize(QtCore.QSize(120, 40))
        self.pushButton_stop.setMaximumSize(QtCore.QSize(120, 40))
        self.pushButton_stop.setStyleSheet("QPushButton {\n"
"        background-color: rgb(135, 206, 250);\n"
"        color: white;\n"
"        border-radius: 20px;\n"
"        padding: 10px;\n"
"        font-size: 16px;\n"
"        border: none;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(70, 130, 180);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(30, 144, 255);\n"
"    }\n"
"    QPushButton:disabled {\n"
"        background-color: rgb(192, 192, 192);\n"
"    }")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout.addWidget(self.pushButton_stop)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_9.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMinimumSize(QtCore.QSize(350, 20))
        self.label_13.setMaximumSize(QtCore.QSize(350, 20))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setMinimumSize(QtCore.QSize(120, 40))
        self.pushButton_reset.setMaximumSize(QtCore.QSize(120, 40))
        self.pushButton_reset.setStyleSheet("QPushButton {\n"
"        background-color: rgb(135, 206, 250);\n"
"        color: white;\n"
"        border-radius: 20px;\n"
"        padding: 10px;\n"
"        font-size: 16px;\n"
"        border: none;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(70, 130, 180);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(30, 144, 255);\n"
"    }\n"
"    QPushButton:disabled {\n"
"        background-color: rgb(192, 192, 192);\n"
"    }")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_2.addWidget(self.pushButton_reset)
        self.pushButton_eject = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_eject.setMinimumSize(QtCore.QSize(120, 40))
        self.pushButton_eject.setMaximumSize(QtCore.QSize(120, 40))
        self.pushButton_eject.setStyleSheet("QPushButton {\n"
"        background-color: rgb(135, 206, 250);\n"
"        color: white;\n"
"        border-radius: 20px;\n"
"        padding: 10px;\n"
"        font-size: 16px;\n"
"        border: none;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(70, 130, 180);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(30, 144, 255);\n"
"    }\n"
"    QPushButton:disabled {\n"
"        background-color: rgb(192, 192, 192);\n"
"    }")
        self.pushButton_eject.setObjectName("pushButton_eject")
        self.horizontalLayout_2.addWidget(self.pushButton_eject)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMinimumSize(QtCore.QSize(350, 20))
        self.label_14.setMaximumSize(QtCore.QSize(350, 20))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.pushButton_move2view = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_move2view.setStyleSheet("QPushButton {\n"
"        background-color: rgb(135, 206, 250);\n"
"        color: white;\n"
"        border-radius: 20px;\n"
"        padding: 10px;\n"
"        font-size: 16px;\n"
"        border: none;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(70, 130, 180);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(30, 144, 255);\n"
"    }\n"
"    QPushButton:disabled {\n"
"        background-color: rgb(192, 192, 192);\n"
"    }")
        self.pushButton_move2view.setObjectName("pushButton_move2view")
        self.verticalLayout_7.addWidget(self.pushButton_move2view)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setMinimumSize(QtCore.QSize(350, 20))
        self.label_15.setMaximumSize(QtCore.QSize(350, 20))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_50Xlive = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_50Xlive.setStyleSheet("QPushButton {\n"
"        background-color: rgb(135, 206, 250);\n"
"        color: white;\n"
"        border-radius: 20px;\n"
"        padding: 10px;\n"
"        font-size: 16px;\n"
"        border: none;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(70, 130, 180);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(30, 144, 255);\n"
"    }\n"
"    QPushButton:disabled {\n"
"        background-color: rgb(192, 192, 192);\n"
"    }")
        self.pushButton_50Xlive.setObjectName("pushButton_50Xlive")
        self.verticalLayout_4.addWidget(self.pushButton_50Xlive)
        self.pushButton_20Xlive = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20Xlive.setStyleSheet("QPushButton {\n"
"        background-color: rgb(135, 206, 250);\n"
"        color: white;\n"
"        border-radius: 20px;\n"
"        padding: 10px;\n"
"        font-size: 16px;\n"
"        border: none;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(70, 130, 180);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(30, 144, 255);\n"
"    }\n"
"    QPushButton:disabled {\n"
"        background-color: rgb(192, 192, 192);\n"
"    }")
        self.pushButton_20Xlive.setObjectName("pushButton_20Xlive")
        self.verticalLayout_4.addWidget(self.pushButton_20Xlive)
        self.pushButton_live_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_live_close.setStyleSheet("QPushButton {\n"
"        background-color: rgb(135, 206, 250);\n"
"        color: white;\n"
"        border-radius: 20px;\n"
"        padding: 10px;\n"
"        font-size: 16px;\n"
"        border: none;\n"
"        text-align: center;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(70, 130, 180);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(30, 144, 255);\n"
"    }\n"
"    QPushButton:disabled {\n"
"        background-color: rgb(192, 192, 192);\n"
"    }")
        self.pushButton_live_close.setObjectName("pushButton_live_close")
        self.verticalLayout_4.addWidget(self.pushButton_live_close)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_x = QtWidgets.QLabel(self.centralwidget)
        self.label_x.setMinimumSize(QtCore.QSize(0, 21))
        self.label_x.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_x.setText("")
        self.label_x.setObjectName("label_x")
        self.horizontalLayout_6.addWidget(self.label_x)
        self.label_y = QtWidgets.QLabel(self.centralwidget)
        self.label_y.setMinimumSize(QtCore.QSize(0, 21))
        self.label_y.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_y.setText("")
        self.label_y.setObjectName("label_y")
        self.horizontalLayout_6.addWidget(self.label_y)
        self.label_z = QtWidgets.QLabel(self.centralwidget)
        self.label_z.setMinimumSize(QtCore.QSize(0, 21))
        self.label_z.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_z.setText("")
        self.label_z.setObjectName("label_z")
        self.horizontalLayout_6.addWidget(self.label_z)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1532, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BIOscope"))
        self.label_16.setText(_translate("MainWindow", "扫描倍数"))
        self.comboBox_multiple.setItemText(0, _translate("MainWindow", "50x"))
        self.label_10.setText(_translate("MainWindow", "扫描模式"))
        self.comboBox_mode.setItemText(0, _translate("MainWindow", "快速扫描一"))
        self.comboBox_mode.setItemText(1, _translate("MainWindow", "快速扫描二"))
        self.comboBox_mode.setItemText(2, _translate("MainWindow", "精准扫描"))
        self.label_11.setText(_translate("MainWindow", "区域选择"))
        self.comboBox_region.setItemText(0, _translate("MainWindow", "4mmx4mm"))
        self.comboBox_region.setItemText(1, _translate("MainWindow", "8mmx8mm"))
        self.comboBox_region.setItemText(2, _translate("MainWindow", "15mmx15mm"))
        self.pushButton_save_setup.setText(_translate("MainWindow", "确认模式"))
        self.label_12.setText(_translate("MainWindow", "扫描操作"))
        self.pushButton_initialize.setText(_translate("MainWindow", "显微镜初始化"))
        self.pushButton_run.setText(_translate("MainWindow", "开始扫描"))
        self.pushButton_stop.setText(_translate("MainWindow", "停止"))
        self.label_13.setText(_translate("MainWindow", "非扫描阶段操作"))
        self.pushButton_reset.setText(_translate("MainWindow", "复位"))
        self.pushButton_eject.setText(_translate("MainWindow", "弹出玻片"))
        self.label_14.setText(_translate("MainWindow", "复查操作"))
        self.pushButton_move2view.setText(_translate("MainWindow", "移动到该视野"))
        self.label_15.setText(_translate("MainWindow", "其他操作"))
        self.pushButton_50Xlive.setText(_translate("MainWindow", "打开50X实时"))
        self.pushButton_20Xlive.setText(_translate("MainWindow", "打开20X实时"))
        self.pushButton_live_close.setText(_translate("MainWindow", "关闭实时"))
